services:
  backend:
    build:
      context: ./flask-server
      dockerfile: ../Dockerfile.backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    env_file:
      - ./flask-server/.env
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: vite-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true   # enables file watch polling on Windows
    command: sh -c "npm run dev -- --host"

